name: CI/CD

on:
  # Push on main excluding tags
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: CI/CD
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Swift Package Manager cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: |
          xcodebuild test -project ORLib.xcodeproj -sdk iphoneos \
          -destination 'platform=iOS Simulator,name=iPhone 16' -scheme ORLib
