name: Release

on:
  # Manual trigger
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:

  build:
    name: Release
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get ORLib version
        id: orlib_version
        run: |
          echo "version=$(xcodebuild -project ORLib.xcodeproj -scheme ORLib -destination generic/platform=iOS -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =')" >> $GITHUB_OUTPUT

      # When the 'github.token' is used events are not generated to prevent users from accidentally creating recursive workflow runs.
      # See: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      - name: Create release
        run: |
          git tag $ORLIB_VERSION
          git push origin tag $ORLIB_VERSION
          gh release create $ORLIB_VERSION --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          ORLIB_VERSION: ${{ steps.orlib_version.outputs.version }}
